"""initial schema

Revision ID: 901288cbf225
Revises:
Create Date: 2026-05-17 14:42:19.819358

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "901288cbf225"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_quality_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_stat_date"))

    op.drop_table("data_quality_metrics")
    op.drop_table("dog_price")
    with op.batch_alter_table("crawl_performance_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_start_time"))
        batch_op.drop_index(batch_op.f("idx_task_id"))
        batch_op.drop_index(batch_op.f("task_id"))

    op.drop_table("crawl_performance_log")
    op.drop_table("jd_dogs2")
    with op.batch_alter_table("system_performance_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_metric_time"))

    op.drop_table("system_performance_metrics")
    op.drop_table("dashboard_summary")
    with op.batch_alter_table("jd_dogs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_dog_name"))
        batch_op.drop_index(batch_op.f("idx_pet_level"))
        batch_op.drop_index(batch_op.f("idx_price"))
        batch_op.drop_index(batch_op.f("idx_price_pet_level"))
        batch_op.drop_index(batch_op.f("idx_shop_name"))

    op.drop_table("jd_dogs")
    op.drop_table("boqi")
    with op.batch_alter_table("daily_summary_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_report_date"))
        batch_op.drop_index(batch_op.f("report_date"))

    op.drop_table("daily_summary_report")
    op.drop_table("dog_wykl")
    op.drop_table("dog_boqi")
    with op.batch_alter_table("price_trend_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_breed_name"))
        batch_op.drop_index(batch_op.f("idx_stat_date"))
        batch_op.drop_index(batch_op.f("unique_date_breed"))

    op.drop_table("price_trend_daily")
    op.drop_table("dog_food_data")
    with op.batch_alter_table("user_behavior_analytics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_action_time"))
        batch_op.drop_index(batch_op.f("idx_action_type"))
        batch_op.drop_index(batch_op.f("idx_session_id"))
        batch_op.drop_index(batch_op.f("idx_user_id"))

    op.drop_table("user_behavior_analytics")
    with op.batch_alter_table("breed_popularity_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_breed_name"))
        batch_op.drop_index(batch_op.f("idx_popularity_score"))
        batch_op.drop_index(batch_op.f("idx_stat_date"))
        batch_op.drop_index(batch_op.f("unique_popularity_date_breed"))

    op.drop_table("breed_popularity_stats")
    op.drop_table("dog_gjw")
    op.drop_table("dog_jd")
    with op.batch_alter_table("app_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.alter_column(
            "last_used_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_index(batch_op.f("access_token"))
        batch_op.drop_index(batch_op.f("idx_access_token"))
        batch_op.drop_index(batch_op.f("idx_refresh_token"))
        batch_op.drop_index(batch_op.f("refresh_token"))
        batch_op.create_index(
            batch_op.f("ix_app_tokens_access_token"), ["access_token"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_app_tokens_refresh_token"), ["refresh_token"], unique=True
        )
        batch_op.drop_constraint(batch_op.f("app_tokens_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"),
            type_=sa.Text(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "feedback_comment",
            existing_type=mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("user_activity_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_constraint(
            batch_op.f("user_activity_logs_ibfk_1"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("user_favorites", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_constraint(
            batch_op.f("user_favorites_ibfk_1"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("user_favorites_ibfk_2"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "dog_breeds", ["breed_id"], ["id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=mysql.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text(
                "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
            ),
        )
        batch_op.drop_constraint(batch_op.f("user_profiles_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("user_profiles_ibfk_1"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text(
                "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
            ),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("user_favorites", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("user_favorites_ibfk_2"),
            "dog_breeds",
            ["breed_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("user_favorites_ibfk_1"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("user_activity_logs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("user_activity_logs_ibfk_1"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "feedback_comment",
            existing_type=sa.Text(),
            type_=mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "content",
            existing_type=sa.Text(),
            type_=mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"),
            existing_nullable=False,
        )

    with op.batch_alter_table("app_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("app_tokens_ibfk_1"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_app_tokens_refresh_token"))
        batch_op.drop_index(batch_op.f("ix_app_tokens_access_token"))
        batch_op.create_index(
            batch_op.f("refresh_token"), ["refresh_token"], unique=True
        )
        batch_op.create_index(
            batch_op.f("idx_refresh_token"), ["refresh_token"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_access_token"), ["access_token"], unique=False
        )
        batch_op.create_index(batch_op.f("access_token"), ["access_token"], unique=True)
        batch_op.alter_column(
            "last_used_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=mysql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    op.create_table(
        "dog_jd",
        sa.Column(
            "dog_id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("product_number", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("shop", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("immune_deworming", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("pet_level", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("variety", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("size", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("pedigree_certificate", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("hair_length", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("pet_age", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("dog_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "dog_gjw",
        sa.Column(
            "dog_id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("img_link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("dog_name", mysql.VARCHAR(length=20), nullable=True),
        sa.Column("english_name", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("size", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("life", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("dog_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "breed_popularity_stats",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("stat_date", sa.DATE(), nullable=False, comment="统计日期"),
        sa.Column(
            "breed_name", mysql.VARCHAR(length=100), nullable=False, comment="品种名称"
        ),
        sa.Column(
            "total_records",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="数据记录数",
        ),
        sa.Column("avg_price", mysql.FLOAT(), nullable=True, comment="平均价格"),
        sa.Column(
            "search_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="搜索次数",
        ),
        sa.Column(
            "view_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="查看次数",
        ),
        sa.Column(
            "favorite_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="收藏次数",
        ),
        sa.Column(
            "share_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="分享次数",
        ),
        sa.Column(
            "ai_query_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="AI查询次数",
        ),
        sa.Column(
            "popularity_score",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="热度评分(0-100)",
        ),
        sa.Column(
            "rank",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
            comment="排名",
        ),
        sa.Column(
            "prev_week_score", mysql.FLOAT(), nullable=True, comment="上周热度评分"
        ),
        sa.Column("score_change", mysql.FLOAT(), nullable=True, comment="评分变化"),
        sa.Column(
            "trend", mysql.ENUM("up", "down", "stable"), nullable=True, comment="趋势"
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="品种热度统计表",
        mysql_comment="品种热度统计表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("breed_popularity_stats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("unique_popularity_date_breed"),
            ["stat_date", "breed_name"],
            unique=True,
        )
        batch_op.create_index(batch_op.f("idx_stat_date"), ["stat_date"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_popularity_score"), ["popularity_score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_breed_name"), ["breed_name"], unique=False
        )

    op.create_table(
        "user_behavior_analytics",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
            comment="用户ID（匿名为NULL）",
        ),
        sa.Column(
            "session_id", mysql.VARCHAR(length=100), nullable=True, comment="会话ID"
        ),
        sa.Column(
            "action_type", mysql.VARCHAR(length=50), nullable=False, comment="行为类型"
        ),
        sa.Column(
            "target_id", mysql.VARCHAR(length=100), nullable=True, comment="目标ID"
        ),
        sa.Column(
            "target_name", mysql.VARCHAR(length=200), nullable=True, comment="目标名称"
        ),
        sa.Column("metadata", mysql.TEXT(), nullable=True, comment="附加信息(JSON)"),
        sa.Column(
            "duration_seconds", mysql.FLOAT(), nullable=True, comment="停留时长(秒)"
        ),
        sa.Column(
            "device_type", mysql.VARCHAR(length=20), nullable=True, comment="设备类型"
        ),
        sa.Column("browser", mysql.VARCHAR(length=50), nullable=True, comment="浏览器"),
        sa.Column(
            "ip_address", mysql.VARCHAR(length=50), nullable=True, comment="IP地址"
        ),
        sa.Column(
            "action_time",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
            comment="行为时间",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_behavior_analytics_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="用户行为分析表",
        mysql_comment="用户行为分析表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("user_behavior_analytics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_action_type"), ["action_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_action_time"), ["action_time"], unique=False
        )

    op.create_table(
        "dog_food_data",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "brand",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=True,
        ),
        sa.Column(
            "product_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=200),
            nullable=True,
        ),
        sa.Column("price", mysql.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "weight",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=True,
        ),
        sa.Column(
            "level",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=True,
        ),
        sa.Column(
            "shop_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=True,
        ),
        sa.Column(
            "origin",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=True,
        ),
        sa.Column(
            "ingredient_analysis",
            mysql.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "price_trend_daily",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("stat_date", sa.DATE(), nullable=False, comment="统计日期"),
        sa.Column(
            "breed_name", mysql.VARCHAR(length=100), nullable=False, comment="品种名称"
        ),
        sa.Column("avg_price", mysql.FLOAT(), nullable=True, comment="平均价格"),
        sa.Column("min_price", mysql.FLOAT(), nullable=True, comment="最低价格"),
        sa.Column("max_price", mysql.FLOAT(), nullable=True, comment="最高价格"),
        sa.Column("median_price", mysql.FLOAT(), nullable=True, comment="中位数价格"),
        sa.Column("price_std", mysql.FLOAT(), nullable=True, comment="价格标准差"),
        sa.Column(
            "record_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="记录数量",
        ),
        sa.Column(
            "shop_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="店铺数量",
        ),
        sa.Column(
            "prev_day_avg_price", mysql.FLOAT(), nullable=True, comment="前一日平均价格"
        ),
        sa.Column("price_change", mysql.FLOAT(), nullable=True, comment="价格变化额"),
        sa.Column(
            "price_change_percent",
            mysql.FLOAT(),
            nullable=True,
            comment="价格变化百分比",
        ),
        sa.Column(
            "fresh_data_ratio",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="新鲜数据占比",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="价格趋势日统计表",
        mysql_comment="价格趋势日统计表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("price_trend_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("unique_date_breed"), ["stat_date", "breed_name"], unique=True
        )
        batch_op.create_index(batch_op.f("idx_stat_date"), ["stat_date"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_breed_name"), ["breed_name"], unique=False
        )

    op.create_table(
        "dog_boqi",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("en_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("dog_character", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("ancestry", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("easy_sick", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("life", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("views", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("ranking", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "dog_wykl",
        sa.Column(
            "food_id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("img_src", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("food_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("discount_price", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("price", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("origin", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("food_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "daily_summary_report",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("report_date", sa.DATE(), nullable=False, comment="报告日期"),
        sa.Column(
            "summary_data", mysql.TEXT(), nullable=False, comment="汇总数据(JSON)"
        ),
        sa.Column(
            "generation_status",
            mysql.ENUM("pending", "generating", "completed", "failed"),
            server_default=sa.text("'pending'"),
            nullable=True,
            comment="生成状态",
        ),
        sa.Column("generated_at", mysql.DATETIME(), nullable=True, comment="生成时间"),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="每日汇总报告表",
        mysql_comment="每日汇总报告表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("daily_summary_report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("report_date"), ["report_date"], unique=True)
        batch_op.create_index(
            batch_op.f("idx_report_date"), ["report_date"], unique=False
        )

    op.create_table(
        "boqi",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("product_number", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("sold", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "num_reviews",
            mysql.INTEGER(display_width=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "jd_dogs",
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("price", mysql.FLOAT(), nullable=True),
        sa.Column(
            "number",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("shop_name", mysql.VARCHAR(length=55), nullable=True),
        sa.Column("dog_name", mysql.VARCHAR(length=25), nullable=True),
        sa.Column("pet_level", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("size", mysql.VARCHAR(length=25), nullable=True),
        sa.Column("weight", mysql.FLOAT(), nullable=True),
        sa.Column("hair_length", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("pet_age", mysql.VARCHAR(length=50), nullable=True),
        sa.Column(
            "crawl_time",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
            comment="爬取时间",
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("number"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("jd_dogs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_shop_name"), ["shop_name"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_price_pet_level"), ["price", "pet_level"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_price"), ["price"], unique=False)
        batch_op.create_index(batch_op.f("idx_pet_level"), ["pet_level"], unique=False)
        batch_op.create_index(batch_op.f("idx_dog_name"), ["dog_name"], unique=False)

    op.create_table(
        "dashboard_summary",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "total_dogs",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("avg_price", mysql.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "total_shops",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_breeds",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("top_breeds", mysql.JSON(), nullable=True),
        sa.Column("top_shops", mysql.JSON(), nullable=True),
        sa.Column("price_dist", mysql.JSON(), nullable=True),
        sa.Column(
            "level_pet",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "level_blood",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "system_performance_metrics",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "metric_time", mysql.DATETIME(), nullable=False, comment="统计时间点"
        ),
        sa.Column(
            "time_window",
            mysql.VARCHAR(length=20),
            server_default=sa.text("'1min'"),
            nullable=True,
            comment="时间窗口",
        ),
        sa.Column(
            "total_requests",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="总请求数",
        ),
        sa.Column(
            "avg_response_time",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="平均响应时间(ms)",
        ),
        sa.Column(
            "p95_response_time",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="P95响应时间(ms)",
        ),
        sa.Column(
            "p99_response_time",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="P99响应时间(ms)",
        ),
        sa.Column(
            "error_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="错误数",
        ),
        sa.Column(
            "error_rate",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="错误率(%)",
        ),
        sa.Column(
            "endpoint_stats", mysql.TEXT(), nullable=True, comment="端点统计(JSON)"
        ),
        sa.Column(
            "active_users",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="活跃用户数",
        ),
        sa.Column(
            "concurrent_connections",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="并发连接数",
        ),
        sa.Column(
            "db_query_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="数据库查询数",
        ),
        sa.Column(
            "db_avg_query_time",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="数据库平均查询时间(ms)",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="系统性能指标表",
        mysql_comment="系统性能指标表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("system_performance_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_metric_time"), ["metric_time"], unique=False
        )

    op.create_table(
        "jd_dogs2",
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("price", mysql.FLOAT(), nullable=True),
        sa.Column(
            "number",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("shop_name", mysql.VARCHAR(length=55), nullable=True),
        sa.Column("dog_name", mysql.VARCHAR(length=25), nullable=True),
        sa.Column("pet_level", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("size", mysql.VARCHAR(length=25), nullable=True),
        sa.Column("weight", mysql.FLOAT(), nullable=True),
        sa.Column("hair_length", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("pet_age", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("number"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "crawl_performance_log",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "task_id", mysql.VARCHAR(length=100), nullable=False, comment="任务ID"
        ),
        sa.Column(
            "keywords", mysql.TEXT(), nullable=True, comment="搜索关键词(JSON数组)"
        ),
        sa.Column("start_time", mysql.DATETIME(), nullable=False, comment="开始时间"),
        sa.Column("end_time", mysql.DATETIME(), nullable=True, comment="结束时间"),
        sa.Column("duration_seconds", mysql.FLOAT(), nullable=True, comment="耗时(秒)"),
        sa.Column(
            "total_found",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="发现总数",
        ),
        sa.Column(
            "success_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="成功爬取数",
        ),
        sa.Column(
            "failed_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="失败数",
        ),
        sa.Column(
            "skipped_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="跳过数(已存在)",
        ),
        sa.Column(
            "requests_per_second",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="请求速度(req/s)",
        ),
        sa.Column(
            "success_rate",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="成功率(%)",
        ),
        sa.Column(
            "avg_response_time",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="平均响应时间(ms)",
        ),
        sa.Column(
            "error_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="错误次数",
        ),
        sa.Column(
            "error_details", mysql.TEXT(), nullable=True, comment="错误详情(JSON)"
        ),
        sa.Column(
            "status",
            mysql.ENUM("success", "partial", "failed"),
            server_default=sa.text("'success'"),
            nullable=True,
            comment="任务状态",
        ),
        sa.Column(
            "triggered_by",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'manual'"),
            nullable=True,
            comment="触发方式",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="爬取性能日志表",
        mysql_comment="爬取性能日志表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("crawl_performance_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("task_id"), ["task_id"], unique=True)
        batch_op.create_index(batch_op.f("idx_task_id"), ["task_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_start_time"), ["start_time"], unique=False
        )

    op.create_table(
        "dog_price",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("links", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("img_src", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("dog_name", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("price", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("Hairy", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("height", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("Origin_wool", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("dog_function", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "data_quality_metrics",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("stat_date", sa.DATE(), nullable=False, comment="统计日期"),
        sa.Column(
            "total_records",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="总记录数",
        ),
        sa.Column(
            "fresh_records",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="新鲜记录数(<24h)",
        ),
        sa.Column(
            "warning_records",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="警告记录数(24-48h)",
        ),
        sa.Column(
            "stale_records",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="过期记录数(>48h)",
        ),
        sa.Column(
            "completeness_rate",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="数据完整率(%)",
        ),
        sa.Column(
            "accuracy_rate",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="数据准确率(%)",
        ),
        sa.Column(
            "duplicate_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="重复记录数",
        ),
        sa.Column(
            "null_price_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="价格为空数量",
        ),
        sa.Column(
            "null_image_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="图片为空数量",
        ),
        sa.Column(
            "freshness_percentage",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="新鲜度百分比",
        ),
        sa.Column(
            "avg_hours_since_crawl",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="平均爬取时长(小时)",
        ),
        sa.Column(
            "max_hours_since_crawl",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="最大爬取时长(小时)",
        ),
        sa.Column(
            "breed_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="品种数量",
        ),
        sa.Column(
            "top_breed",
            mysql.VARCHAR(length=100),
            nullable=True,
            comment="最多记录的品种",
        ),
        sa.Column(
            "top_breed_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="最多记录的品种数量",
        ),
        sa.Column(
            "avg_price",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="平均价格",
        ),
        sa.Column(
            "min_price",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="最低价格",
        ),
        sa.Column(
            "max_price",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="最高价格",
        ),
        sa.Column(
            "price_std",
            mysql.FLOAT(),
            server_default=sa.text("'0'"),
            nullable=True,
            comment="价格标准差",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="数据质量指标表",
        mysql_comment="数据质量指标表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("data_quality_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_stat_date"), ["stat_date"], unique=False)

    # ### end Alembic commands ###
